# =========================================================================
# Copyright (C) 2026. UniRank Authors. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# =========================================================================

QK_Video_Action:
        data_root: ./datasets
        data_format: parquet
        train_data: ./datasets/QK_Video_Action/train/data
        valid_data: ./datasets/QK_Video_Action/valid/data
        test_data: ./datasets/QK_Video_Action/test/data
        train_user_info: ./datasets/QK_Video_Action/train/user_info
        train_item_info: ./datasets/QK_Video_Action/train/item_info
        valid_user_info: ./datasets/QK_Video_Action/valid/user_info
        valid_item_info: ./datasets/QK_Video_Action/valid/item_info
        test_user_info: ./datasets/QK_Video_Action/test/user_info
        test_item_info: ./datasets/QK_Video_Action/test/item_info
        rebuild_dataset: False
        blocked: True
        block_cache_size: 2
        feature_cols:
            - {name: user_index, active: True, dtype: int, type: meta}
            - {name: item_index, active: True, dtype: int, type: meta}
            - {name: seq_len, active: True, dtype: int, type: meta}
            - {name: user_id, active: True, dtype: int, type: categorical, vocab_size: 4996177}
            - {name: item_id, active: True, dtype: int, type: categorical, vocab_size: 3753437, source: item}
            - {name: video_category, active: True, dtype: int, type: categorical, vocab_size: 5, source: item}
            - {name: watching_times, active: True, dtype: int, type: categorical, vocab_size: 419}
            - {name: gender, active: True, dtype: int, type: categorical, vocab_size: 5}
            - {name: age, active: True, dtype: int, type: categorical, vocab_size: 10}
            - {name: action, active: True, dtype: int, type: categorical, vocab_size: 17, source: action}
        label_col:
            - {name: click, dtype: float}
            - {name: follow, dtype: float}
            - {name: like, dtype: float}
            - {name: share, dtype: float}

KuaiRand_Video_Action:
    data_root: ./datasets
    data_format: parquet
    train_data: ./datasets/KuaiRand_Video_Action/train/data
    valid_data: ./datasets/KuaiRand_Video_Action/valid/data
    test_data: ./datasets/KuaiRand_Video_Action/test/data
    train_user_info: ./datasets/KuaiRand_Video_Action/train/user_info
    train_item_info: ./datasets/KuaiRand_Video_Action/train/item_info
    valid_user_info: ./datasets/KuaiRand_Video_Action/valid/user_info
    valid_item_info: ./datasets/KuaiRand_Video_Action/valid/item_info
    test_user_info: ./datasets/KuaiRand_Video_Action/test/user_info
    test_item_info: ./datasets/KuaiRand_Video_Action/test/item_info
    rebuild_dataset: False
    blocked: True
    block_cache_size: 2
    feature_cols:
        - {name: user_index, active: True, dtype: int, type: meta}
        - {name: item_index, active: True, dtype: int, type: meta}
        - {name: seq_len, active: True, dtype: int, type: meta}
        - {name: user_id, active: True, dtype: int, type: categorical, vocab_size: 27286}
        - {name: item_id, active: True, dtype: int, type: categorical, vocab_size: 32038726, source: item}
        - {name: video_type, active: True, dtype: int, type: categorical, vocab_size: 4, source: item}
        - {name: primary_tag, active: True, dtype: int, type: categorical, vocab_size: 60, source: item}
        - {name: music_type, active: True, dtype: int, type: categorical, vocab_size: 8, source: item}
        - {name: duration_bucket, active: True, dtype: int, type: categorical, vocab_size: 8, source: item}
        - {name: user_active_degree, active: True, dtype: int, type: categorical, vocab_size: 11}
        - {name: is_lowactive_period, active: True, dtype: int, type: categorical, vocab_size: 3}
        - {name: is_live_streamer, active: True, dtype: int, type: categorical, vocab_size: 4}
        - {name: is_video_author, active: True, dtype: int, type: categorical, vocab_size: 4}
        - {name: follow_user_num_range, active: True, dtype: int, type: categorical, vocab_size: 10}
        - {name: fans_user_num_range, active: True, dtype: int, type: categorical, vocab_size: 11}
        - {name: friend_user_num_range, active: True, dtype: int, type: categorical, vocab_size: 9}
        - {name: register_days_range, active: True, dtype: int, type: categorical, vocab_size: 10}
        - {name: onehot_feat0, active: True, dtype: int, type: categorical, vocab_size: 4}
        - {name: onehot_feat1, active: True, dtype: int, type: categorical, vocab_size: 9}
        - {name: onehot_feat2, active: True, dtype: int, type: categorical, vocab_size: 52}
        - {name: onehot_feat3, active: True, dtype: int, type: categorical, vocab_size: 1473}
        - {name: onehot_feat4, active: True, dtype: int, type: categorical, vocab_size: 18}
        - {name: onehot_feat5, active: True, dtype: int, type: categorical, vocab_size: 36}
        - {name: onehot_feat6, active: True, dtype: int, type: categorical, vocab_size: 5}
        - {name: onehot_feat7, active: True, dtype: int, type: categorical, vocab_size: 120}
        - {name: onehot_feat8, active: True, dtype: int, type: categorical, vocab_size: 456}
        - {name: onehot_feat9, active: True, dtype: int, type: categorical, vocab_size: 9}
        - {name: onehot_feat10, active: True, dtype: int, type: categorical, vocab_size: 7}
        - {name: onehot_feat11, active: True, dtype: int, type: categorical, vocab_size: 7}
        - {name: onehot_feat12, active: True, dtype: int, type: categorical, vocab_size: 5}
        - {name: onehot_feat13, active: True, dtype: int, type: categorical, vocab_size: 5}
        - {name: onehot_feat14, active: True, dtype: int, type: categorical, vocab_size: 5}
        - {name: onehot_feat15, active: True, dtype: int, type: categorical, vocab_size: 5}
        - {name: onehot_feat16, active: True, dtype: int, type: categorical, vocab_size: 5}
        - {name: onehot_feat17, active: True, dtype: int, type: categorical, vocab_size: 5}
        - {name: tab, active: True, dtype: int, type: categorical, vocab_size: 16}
        - {name: day_of_week, active: True, dtype: int, type: categorical, vocab_size: 8}
        - {name: is_weekend, active: True, dtype: int, type: categorical, vocab_size: 3}
        - {name: hour, active: True, dtype: int, type: categorical, vocab_size: 25}
        - {name: action, active: True, dtype: int, type: categorical, vocab_size: 65, source: action}
    label_col:
        - {name: is_click, dtype: float}
        - {name: is_follow, dtype: float }
        - {name: is_like, dtype: float}
        - {name: is_comment, dtype: float}
        - {name: is_forward, dtype: float}
        - {name: long_view, dtype: float}


TencentGR_10M_Action:
    data_root: ./datasets
    data_format: parquet
    train_data: ./datasets/TencentGR_10M_Action/train/data
    valid_data: ./datasets/TencentGR_10M_Action/valid/data
    test_data: ./datasets/TencentGR_10M_Action/test/data
    train_user_info: ./datasets/TencentGR_10M_Action/train/user_info
    train_item_info: ./datasets/TencentGR_10M_Action/train/item_info
    valid_user_info: ./datasets/TencentGR_10M_Action/valid/user_info
    valid_item_info: ./datasets/TencentGR_10M_Action/valid/item_info
    test_user_info: ./datasets/TencentGR_10M_Action/test/user_info
    test_item_info: ./datasets/TencentGR_10M_Action/test/item_info
    rebuild_dataset: False
    blocked: True
    block_cache_size: 2
    feature_cols:
        - {name: user_index, active: True, dtype: int, type: meta}
        - {name: item_index, active: True, dtype: int, type: meta}
        - {name: seq_len, active: True, dtype: int, type: meta}
        - {name: user_id, active: True, dtype: int, type: categorical, vocab_size: 7706779}
        - {name: item_id, active: True, dtype: int, type: categorical, vocab_size: 17487677, source: item}
        - {name: '100', active: True, dtype: int, type: categorical, vocab_size: 7, source: item}
        - {name: '101', active: True, dtype: int, type: categorical, vocab_size: 54, source: item}
        - {name: '102', active: True, dtype: int, type: categorical, vocab_size: 173463, source: item}
        - {name: '112', active: True, dtype: int, type: categorical, vocab_size: 31, source: item}
        - {name: '114', active: True, dtype: int, type: categorical, vocab_size: 34, source: item}
        - {name: '115', active: True, dtype: int, type: categorical, vocab_size: 989, source: item}
        - {name: '116', active: True, dtype: int, type: categorical, vocab_size: 21, source: item}
        - {name: '117', active: True, dtype: int, type: categorical, vocab_size: 559, source: item}
        - {name: '118', active: True, dtype: int, type: categorical, vocab_size: 1637, source: item}
        - {name: '119', active: True, dtype: int, type: categorical, vocab_size: 4951, source: item}
        - {name: '120', active: True, dtype: int, type: categorical, vocab_size: 4046, source: item}
        - {name: '121', active: True, dtype: int, type: categorical, vocab_size: 5041300, source: item}
        - {name: '122', active: True, dtype: int, type: categorical, vocab_size: 2389, source: item}
        - {name: '103', active: True, dtype: int, type: categorical, vocab_size: 88}
        - {name: '104', active: True, dtype: int, type: categorical, vocab_size: 4}
        - {name: '105', active: True, dtype: int, type: categorical, vocab_size: 8}
        - {name: '109', active: True, dtype: int, type: categorical, vocab_size: 4}
        - {name: '106', active: True, dtype: int, type: sequence, max_len: 5, vocab_size: 15}
        - {name: '107', active: True, dtype: int, type: sequence, max_len: 5, vocab_size: 20}
        - {name: '108', active: True, dtype: int, type: sequence, max_len: 5, vocab_size: 5}
        - {name: '110', active: True, dtype: int, type: sequence, max_len: 5, vocab_size: 3}
        - {name: day_of_week, active: True, dtype: int, type: categorical, vocab_size: 8}
        - {name: is_weekend, active: True, dtype: int, type: categorical, vocab_size: 3}
        - {name: hour, active: True, dtype: int, type: categorical, vocab_size: 25}
        - {name: action, active: True, dtype: int, type: categorical, vocab_size: 4, source: action}
    label_col:
        - {name: is_click, dtype: float}
        - {name: is_conversion, dtype: float}

Taobao_Action:
    data_root: ./datasets
    data_format: parquet
    train_data: ./datasets/Taobao_Action/train/data
    valid_data: ./datasets/Taobao_Action/valid/data
    test_data: ./datasets/Taobao_Action/test/data
    train_user_info: ./datasets/Taobao_Action/train/user_info
    train_item_info: ./datasets/Taobao_Action/train/item_info
    valid_user_info: ./datasets/Taobao_Action/valid/user_info
    valid_item_info: ./datasets/Taobao_Action/valid/item_info
    test_user_info: ./datasets/Taobao_Action/test/user_info
    test_item_info: ./datasets/Taobao_Action/test/item_info
    rebuild_dataset: False
    blocked: True
    block_cache_size: 2
    feature_cols:
        - {name: user_index, active: True, dtype: int, type: meta}
        - {name: item_index, active: True, dtype: int, type: meta}
        - {name: seq_len, active: True, dtype: int, type: meta}
        - {name: user_id, active: True, dtype: int, type: categorical, vocab_size: 470571}
        - {name: item_id, active: True, dtype: int, type: categorical, vocab_size: 846812, source: item}
        - {name: cate_id, active: True, dtype: int, type: categorical, vocab_size: 6409, source: item}
        - {name: campaign_id, active: True, dtype: int, type: categorical, vocab_size: 354106, source: item}
        - {name: customer_id, active: True, dtype: int, type: categorical, vocab_size: 220826, source: item}
        - {name: brand, active: True, dtype: int, type: categorical, vocab_size: 88145, source: item}
        - {name: price_bucket, active: True, dtype: int, type: categorical, vocab_size: 11, source: item}
        - {name: cms_segid, active: True, dtype: int, type: categorical, vocab_size: 99}
        - {name: cms_group_id, active: True, dtype: int, type: categorical, vocab_size: 15}
        - {name: final_gender_code, active: True, dtype: int, type: categorical, vocab_size: 4}
        - {name: age_level, active: True, dtype: int, type: categorical, vocab_size: 9}
        - {name: pvalue_level, active: True, dtype: int, type: categorical, vocab_size: 5}
        - {name: shopping_level, active: True, dtype: int, type: categorical, vocab_size: 5}
        - {name: occupation, active: True, dtype: int, type: categorical, vocab_size: 4}
        - {name: new_user_class_level, active: True, dtype: int, type: categorical, vocab_size: 6}
        - {name: pid, active: True, dtype: int, type: categorical, vocab_size: 4}
        - {name: is_weekend, active: True, dtype: int, type: categorical, vocab_size: 3}
        - {name: hour, active: True, dtype: int, type: categorical, vocab_size: 25}
        - {name: action, active: True, dtype: int, type: categorical, vocab_size: 17, source: action}
    label_col:
        - {name: is_click, dtype: float}
        - {name: cart, dtype: float}
        - {name: fav, dtype: float}
        - {name: buy, dtype: float}

MerRec_Action:
    data_root: ./datasets
    data_format: parquet
    train_data: ./datasets/MerRec_Action/train/data
    valid_data: ./datasets/MerRec_Action/valid/data
    test_data: ./datasets/MerRec_Action/test/data
    train_user_info: ./datasets/MerRec_Action/train/user_info
    train_item_info: ./datasets/MerRec_Action/train/item_info
    valid_user_info: ./datasets/MerRec_Action/valid/user_info
    valid_item_info: ./datasets/MerRec_Action/valid/item_info
    test_user_info: ./datasets/MerRec_Action/test/user_info
    test_item_info: ./datasets/MerRec_Action/test/item_info
    rebuild_dataset: False
    blocked: True
    block_cache_size: 2
    feature_cols:
        - {name: user_index, active: True, dtype: int, type: meta}
        - {name: item_index, active: True, dtype: int, type: meta}
        - {name: seq_len, active: True, dtype: int, type: meta}
        - {name: user_id, active: True, dtype: int, type: categorical, vocab_size: 1697916}
        - {name: item_id, active: True, dtype: int, type: categorical, vocab_size: 43817684, source: item}
        - {name: product_id, active: True, dtype: int, type: categorical, vocab_size: 893620, source: item}
        - {name: price_bucket, active: True, dtype: int, type: categorical, vocab_size: 10, source: item}
        - {name: c0_id, active: True, dtype: int, type: categorical, vocab_size: 18, source: item}
        - {name: c1_id, active: True, dtype: int, type: categorical, vocab_size: 310, source: item}
        - {name: c2_id, active: True, dtype: int, type: categorical, vocab_size: 3042, source: item}
        - {name: brand_id, active: True, dtype: int, type: categorical, vocab_size: 19783, source: item}
        - {name: item_condition_id, active: True, dtype: int, type: categorical, vocab_size: 7, source: item}
        - {name: size_id, active: True, dtype: int, type: categorical, vocab_size: 356, source: item}
        - {name: shipper_id, active: True, dtype: int, type: categorical, vocab_size: 3, source: item}
        - {name: color, active: True, dtype: int, type: categorical, vocab_size: 7311, source: item}
        - {name: session_id, active: True, dtype: int, type: categorical, vocab_size: 3701837}
        - {name: day_of_week, active: True, dtype: int, type: categorical, vocab_size: 8}
        - {name: is_weekend, active: True, dtype: int, type: categorical, vocab_size: 3}
        - {name: hour, active: True, dtype: int, type: categorical, vocab_size: 25}
        - {name: action, active: True, dtype: int, type: categorical, vocab_size: 33, source: action}
    label_col:
        - {name: Like, dtype: float}
        - {name: Cart, dtype: float}
        - {name: Offer, dtype: float}
        - {name: Checkout, dtype: float}
        - {name: Purchase, dtype: float}
